image:
  - Ubuntu
install:
  - sudo apt-get update
  - sudo apt-get --assume-yes install gcc-multilib g++-multilib
build_script:
  - wget https://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz
  - tar -xf gcc-7.4.0.tar.gz
  - mkdir build-gcc
  - cd build-gcc
  - mkdir build-libgcc
  - cd build-libgcc
  - chmod 755 ../../gcc-7.4.0/libgcc/configure
  - ../../gcc-7.4.0/libgcc/configure --disable-shared --disable-decimal-float --disable-vtable-verify
  - make CFLAGS='-O3 -fno-PIC -fno-gnu-unique -flto=jobserver -fno-fat-lto-objects' CPPFLAGS='-O3 -fno-PIC -fno-gnu-unique -flto=jobserver -fno-fat-lto-objects'
  - cd ../..
