image:
  - Ubuntu
install:
  - sudo apt-get update
  - sudo apt-get --assume-yes install gcc-multilib g++-multilib
  - sudo apt-get --assume-yes install libgmp-dev libmpfr-dev libmpc-dev
build_script:
  - wget https://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz
  - tar -xf gcc-7.4.0.tar.gz
  - mkdir build
  - cd build
  - mkdir build-gcc
  - cd build-gcc
  - ../../gcc-7.4.0/configure --with-multilib-list=m32 --disable-shared --enable-languages=c,c++ --disable-host-shared --enable-threads=posix --with-cpu-32=i686 --disable-gnu-indirect-function --disable-bootstrap --disable-checking --disable-gnu-unique-object
  - make
  - cd ../..
artifacts:
  - path: 'build/build-gcc/config.log'