image:
  - Ubuntu
install:
  - sudo apt-get update
  - sudo apt-get --assume-yes install gcc-multilib g++-multilib
  - sudo apt-get --assume-yes install libgmp-dev libmpfr-dev libmpc-dev
  - sudo dpkg --add-architecture i386
build_script:
  - wget https://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz
  - tar -xf gcc-7.4.0.tar.gz
  - mkdir build
  - cd build
  - mkdir build-gcc
  - cd build-gcc
  - ../../gcc-7.4.0/configure --with-multilib-list=m32 --disable-shared --enable-languages=c,c++ --disable-host-shared --enable-threads=posix --disable-gnu-indirect-function --disable-checking --disable-gnu-unique-object --disable-bootstrap
  - ../../gcc-7.4.0/libstdc++-v3/configure --disable-shared
  - make
  - cd ../..
on_failure:
  - appveyor PushArtifact build/build-gcc/x86_64-pc-linux-gnu/libgomp/config.log
