image: Visual Studio 2017
clone_folder: C:\Projects\TestContinuousIntegration
platform: x86
configuration: Release
build_script:
  - mkdir build_%CONFIGURATION%
  - cd build_%CONFIGURATION%
  - cmake ..
  - cd ..
  - cmake --build build_%CONFIGURATION% --config %CONFIGURATION%
artifacts:
  - path: 'build_*\*\*.exe'