image:
  - Visual Studio 2017
  - Ubuntu
build_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_VERBOSE_MAKEFILE=1
  - cd ..
  - cmake --build build --config Debug
artifacts:
  - path: 'build\bin\*.dll'
  - path: 'build\**\*.so'