environment:
  matrix:
  - job_name: Linux Ubuntu1804
    job_allow_cancellation: true
    job_depends_on: Linux Ubuntu1604, Linux Ubuntu 1804_2
    appveyor_build_worker_image: Ubuntu
  - job_name: Linux Ubuntu1604
    job_allow_cancellation: false
    appveyor_build_worker_image: Ubuntu1604
  - job_name: Linux Ubuntu1804_2
    job_allow_cancellation: false
    appveyor_build_worker_image: Ubuntu1804
install:
  - sudo apt-get update
  - sudo apt-get --assume-yes install gcc-multilib g++-multilib
build_script:
  - wget https://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz
  - tar -xf gcc-7.4.0.tar.gz
  - find gcc-7.4.0/libstdc++-v3/libsupc++ -type f -exec sed -i '/^#pragma GCC visibility/ s/^/\/\//' {} \;
  - sed -i 's/_GLIBCXX_WEAK_DEFINITION//' gcc-7.4.0/libstdc++-v3/libsupc++/del_op.cc
  - mkdir build-gcc
  - cd build-gcc
  - mkdir build-libstdc++
  - cd build-libstdc++
  - ../../gcc-7.4.0/libstdc++-v3/configure --enable-multilib --enable-clocale --enable-threads=posix --enable-libstdcxx-threads --enable-libstdcxx-time=rt --enable-cxx-flags='-O3 -flto=jobserver -fno-fat-lto-objects -fno-PIC -fno-gnu-unique -fvisibility=hidden -fvisibility-inlines-hidden' --disable-libstdcxx-visibility --disable-libstdcxx-verbose --disable-shared --disable-vtable-verify
  - make
  - cd ../..
artifacts:
  - path: build-gcc/32/build-libstdc++/src/.libs/libstdc++.a
