image:
  - Visual Studio 2017
  - Ubuntu
build_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  - cmake --build build --config Debug
artifacts:
  - path: 'build\bin\*.*'