image: Visual Studio 2019
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
clone_folder: C:\Projects\TestContinuousIntegration
platform: x86
configuration: Release
build:
  project: Project1.sln
  verbosity: detailed