image: Visual Studio 2017
clone_folder: C:\Projects\TestContinuousIntegration
platform: x86
configuration: Release
build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  - cmake --build build_$configuration --config $configuration
artifacts:
  - path: 'build_*\*\*.exe'